// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notwork.Api.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Notwork.Api.Migrations
{
    [DbContext(typeof(NotworkContext))]
    partial class NotworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Notwork.Api.Contexts.Models.Ping", b =>
                {
                    b.Property<int>("PingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ping_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PingId")
                        .HasName("pk_pings");

                    b.ToTable("pings");
                });
#pragma warning restore 612, 618
        }
    }
}
